### ISSUE TITLE
Nessuna verifica dell'input

### ISSUE THREAD

**Issue by LoZack19** [FrancescoLFM/Lumenaria-Utilities-bot#3]
https://github.com/FrancescoLFM/Lumenaria-Utilities-bot/blob/46d885d996719df4301af6f25ffce5a484b1dd3c/commands/Add.py#L12

1. Devi verificare che vengano inserite solo tre parole o meno, ma non di più, e non troppo lunghe
2. Segnala errori per input invalidi

Consiglio: spezzetta in token, copia i primi tre token, verificando che siano inferiori in lunghezza a 30

**Comment by FrancescoLFM** [comment]
Risolto!
